apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\PROGRAMDATA\CHOCOLATEY\lib\kubernetes-kompose\tools\kompose.exe
      --file ../docker-compose-eks.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: products-service
  name: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: products-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\PROGRAMDATA\CHOCOLATEY\lib\kubernetes-kompose\tools\kompose.exe
          --file ../docker-compose-eks.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: products-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: 326608040956.dkr.ecr.us-east-2.amazonaws.com/widgets-are-us/products-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: products-service
          ports:
            - containerPort: 8074
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
